import os
import smtplib
from email.message import EmailMessage
from dotenv import load_dotenv

# Load .env
load_dotenv()

MAIL_USERNAME = os.getenv("MAIL_USERNAME")
MAIL_PASSWORD = os.getenv("MAIL_PASSWORD")
MAIL_SERVER = os.getenv("MAIL_SERVER", "smtp.gmail.com")
MAIL_PORT = int(os.getenv("MAIL_PORT", 465))

# Debug prints
print("========== EMAIL CONFIG ==========")
print("MAIL_USERNAME:", MAIL_USERNAME)
print("MAIL_SERVER:", MAIL_SERVER)
print("MAIL_PORT:", MAIL_PORT)
print("PASSWORD_LOADED:", MAIL_PASSWORD is not None)
print("==================================")


def send_email_with_pdf(to_email, patient_name, pdf_path):
    try:
        msg = EmailMessage()

        msg["Subject"] = "AI Brain Tumor Detection Report"
        msg["From"] = MAIL_USERNAME
        msg["To"] = to_email

        msg.set_content(
            f"""
Hello {patient_name},

Your AI-generated Brain Tumor Analysis Report is attached.

This report contains:
• Tumor Prediction
• Confidence Score
• Grad-CAM Visualization
• AI Summary

Important:
This report is generated by an AI system and should be reviewed by a qualified radiologist before making clinical decisions.

Regards,
AI Brain Tumor Detection System
"""
        )

        # Attach PDF
        with open(pdf_path, "rb") as f:
            pdf_data = f.read()

        msg.add_attachment(
            pdf_data,
            maintype="application",
            subtype="pdf",
            filename="Brain_Tumor_Report.pdf"
        )

        print(f"Sending email to: {to_email}")

        with smtplib.SMTP_SSL(MAIL_SERVER, MAIL_PORT) as server:
            server.login(MAIL_USERNAME, MAIL_PASSWORD)
            server.send_message(msg)

        print("Email sent successfully!")

        return True

    except Exception as e:
        print("EMAIL ERROR:", str(e))
        return False