from reportlab.platypus import (
    SimpleDocTemplate, Paragraph, Spacer, Image, PageBreak,
    Table, TableStyle
)
from reportlab.lib import colors
from reportlab.lib.styles import getSampleStyleSheet
from reportlab.lib import enums
from reportlab.lib.units import inch
from reportlab.lib.pagesizes import A4
from datetime import datetime
import qrcode
import os

def create_pdf(
    report_id,
    patient_name,
    patient_age,
    patient_email,
    tumor_type,
    confidence,
    probabilities,
    original_mri_path,
    gradcam_path,
    probability_chart_path,
    ai_summary
):
    os.makedirs("static/reports", exist_ok=True)
    os.makedirs("static/qr", exist_ok=True)

    pdf_path = f"static/reports/{report_id}.pdf"
    qr_path = f"static/qr/{report_id}.png"

    qr = qrcode.make(report_id)
    qr.save(qr_path)

    doc = SimpleDocTemplate(pdf_path, pagesize=A4)
    styles = getSampleStyleSheet()
    story = []

    title = Paragraph(
        "<b>AI BRAIN TUMOR DETECTION CENTER</b>",
        styles["Title"]
    )
    story.append(title)
    story.append(Spacer(1, 12))

    story.append(Paragraph(f"<b>Report ID:</b> {report_id}", styles["Normal"]))
    story.append(Paragraph(f"<b>Date:</b> {datetime.now()}", styles["Normal"]))
    story.append(Spacer(1, 10))

    if os.path.exists(qr_path):
        story.append(Image(qr_path, width=1.2*inch, height=1.2*inch))

    patient_table = Table([
        ["Patient Name", patient_name],
        ["Age", patient_age],
        ["Email", patient_email],
        ["Tumor Type", tumor_type],
        ["Confidence", f"{confidence:.2f}%"]
    ], colWidths=[150, 300])

    patient_table.setStyle(TableStyle([
        ('GRID', (0,0), (-1,-1), 1, colors.black),
        ('BACKGROUND', (0,0), (0,-1), colors.lightgrey),
    ]))

    story.append(patient_table)
    story.append(Spacer(1, 15))

    story.append(Paragraph("<b>AI SUMMARY</b>", styles["Heading2"]))
    story.append(Paragraph(ai_summary, styles["BodyText"]))
    story.append(Spacer(1, 15))

    prob_data = [["Class", "Probability (%)"]]
    for k, v in probabilities.items():
        prob_data.append([k, str(v)])

    prob_table = Table(prob_data, colWidths=[200, 200])
    prob_table.setStyle(TableStyle([
        ('GRID', (0,0), (-1,-1), 1, colors.black),
        ('BACKGROUND', (0,0), (-1,0), colors.lightblue),
    ]))

    story.append(Paragraph("<b>Probability Distribution</b>", styles["Heading2"]))
    story.append(prob_table)

    if os.path.exists(probability_chart_path):
        story.append(Spacer(1, 15))
        story.append(Image(probability_chart_path, width=4.5*inch, height=3*inch))

    story.append(PageBreak())

    story.append(Paragraph("<b>Original MRI Scan</b>", styles["Heading1"]))
    if os.path.exists(original_mri_path):
        story.append(Image(original_mri_path, width=5*inch, height=4*inch))

    story.append(Spacer(1, 15))

    story.append(Paragraph("<b>Grad-CAM Visualization</b>", styles["Heading1"]))
    if os.path.exists(gradcam_path):
        story.append(Image(gradcam_path, width=5*inch, height=4*inch))

    story.append(PageBreak())

    story.append(Paragraph("<b>Clinical Recommendation</b>", styles["Heading2"]))

    recommendation = f"""
    Based on the AI analysis, the predicted class is <b>{tumor_type}</b>.
    Further consultation with a neurologist/radiologist is recommended.
    Clinical correlation and additional investigations may be required.
    """
    story.append(Paragraph(recommendation, styles["BodyText"]))

    story.append(Spacer(1, 20))

    disclaimer = """
    <b>Disclaimer:</b><br/>
    This report is generated by an Artificial Intelligence system and is intended
    only for decision support. Final diagnosis should always be confirmed by a
    qualified healthcare professional.
    """
    story.append(Paragraph(disclaimer, styles["BodyText"]))

    story.append(Spacer(1, 30))
    story.append(Paragraph("Generated by AI Brain Tumor Detection Center", styles["Italic"]))

    doc.build(story)
    return pdf_path
